---
cluster_name: "testcluster"
k3s_snapshotter: "native"
k3s_node_name: "{{ cluster_name }}-master"
k3s_config_dir: "/etc/rancher/k3s"
k3s_config_file: "{{ k3s_config_dir }}/config.yaml"
k3s_kubeconfig: "{{ k3s_config_dir }}/k3s.yaml"
k3s_ansible_kubeconfig: "/home/ansible/.kube/config"
k3s_api_port: 6443
k3s_health_retries: 12
k3s_health_delay: 10
k3s_service_name: "k3s-{{ cluster_name }}"
