---
galaxy_info:
  role_name: wireguard_bastion
  description: Configura WireGuard no host bastion
  author: rafaelfriederick
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - wireguard
    - vpn
    - bastion

dependencies: []
