---
# Interface e rede
wg_interface: "wg0"
wg_address: "10.8.0.1/24"
wg_listen_port: 51820

# PostUp/PostDown opcionais (ex.: NAT)
wg_post_up: []
wg_post_down: []

# Lista de peers
# - public_key: "..."
#   allowed_ips: "10.8.0.2/32"
#   endpoint: "meu.ip:51820"
#   persistent_keepalive: 25
wg_peers: []

# IP forwarding
wg_ipv4_forward: true
wg_ipv6_forward: false
