---
- name: Preflight
  include_tasks: preflight.yml

- name: Install
  include_tasks: install.yml

- name: Configure
  include_tasks: config.yml

- name: Records
  include_tasks: records.yml

- name: Service
  include_tasks: service.yml
